// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTG-fTf65T78JpnaJIyFAPNRkgCPDH0MU',
    appId: '1:634230916719:web:a3543115956905eee7af9a',
    messagingSenderId: '634230916719',
    projectId: 'medapp-4a196',
    authDomain: 'medapp-4a196.firebaseapp.com',
    databaseURL: 'https://medapp-4a196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medapp-4a196.appspot.com',
    measurementId: 'G-FBMFZ51H8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArKvRNtMVg5e1uJ1hFh7dIy9PWJkAyJL4',
    appId: '1:634230916719:android:223522b0842c8e36e7af9a',
    messagingSenderId: '634230916719',
    projectId: 'medapp-4a196',
    databaseURL: 'https://medapp-4a196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medapp-4a196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2UwE8eaBZ8cOqmU6fDeHMLF0cdGUs4TQ',
    appId: '1:634230916719:ios:d516baf4215dfd95e7af9a',
    messagingSenderId: '634230916719',
    projectId: 'medapp-4a196',
    databaseURL: 'https://medapp-4a196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medapp-4a196.appspot.com',
    iosClientId: '634230916719-0op2hg467jhmt4daj7gs1k2qgt018kci.apps.googleusercontent.com',
    iosBundleId: 'com.enis.medapp.enis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2UwE8eaBZ8cOqmU6fDeHMLF0cdGUs4TQ',
    appId: '1:634230916719:ios:d516baf4215dfd95e7af9a',
    messagingSenderId: '634230916719',
    projectId: 'medapp-4a196',
    databaseURL: 'https://medapp-4a196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medapp-4a196.appspot.com',
    iosClientId: '634230916719-0op2hg467jhmt4daj7gs1k2qgt018kci.apps.googleusercontent.com',
    iosBundleId: 'com.enis.medapp.enis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTG-fTf65T78JpnaJIyFAPNRkgCPDH0MU',
    appId: '1:634230916719:web:004a1b6ade3c8445e7af9a',
    messagingSenderId: '634230916719',
    projectId: 'medapp-4a196',
    authDomain: 'medapp-4a196.firebaseapp.com',
    databaseURL: 'https://medapp-4a196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medapp-4a196.appspot.com',
    measurementId: 'G-9ZKYSSC59H',
  );
}
